rules = [
  DisableSyntax
  // ExplicitResultTypes // Waiting for: https://github.com/scalacenter/scalafix/issues/1583
  LeakingImplicitClassVal
  NoAutoTupling
  NoValInForComprehension
  OrganizeImports
  RemoveUnused
  RedundantSyntax
]

DisableSyntax.regex = []
DisableSyntax.noReturns = true
DisableSyntax.noXml = true
DisableSyntax.noFinalize = true
DisableSyntax.noValPatterns = true

// Preset rules compatible with Intellij IDEA
// See: https://scalacenter.github.io/scalafix/docs/rules/OrganizeImports.html#intellij_2020_3
OrganizeImports {
  preset = INTELLIJ_2020_3
  targetDialect = Scala3
}
